import '../assets/globals.css';
import { Poppins } from 'next/font/google';

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ['100', '300', '400', '700'],
  display: "swap",
});

export const metadata = {
  title: "make money while traveling",
  keywords: "travel, money, earn, income, remote work, digital nomad",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={poppins.className}
      >
        <main className='py-20'>

        {children}
        </main>
      </body>
    </html>
  );
}
